apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - java
    - backend
  annotations:
    gitlab.com/project-slug: ${{ values.repoUrl | projectSlug }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
