spec:
  component: [sha, version]
  inputs:
    java_version:
      default: "25"
      description: "Java version"
      options: ["21", "25"]
      type: string
    # Standard Component inputs
    component_context_dir:
      default: "./"
      description: "Working directory in which this Component will execute"
      regex: ^([a-z.][a-zA-Z0-9-_/]+)?$
      type: string
    job_name_prefix:
      default: ""
      description: "Prefix for all component jobs"
      regex: ^([a-z][a-z0-9-]+::)*$
      type: string
    job_stage:
      default: "build"
      description: "Pipeline stage in which jobs are run"
      type: string
---
# =============================================================================
# java/build - Builds JAR file
#
# Prescribed behavior:
#   - JAR built using mvn package -DskipTests
#   - Tests are NOT run here (use java/test component)
#
# Output: target/*.jar
# =============================================================================

include:
  - local: /templates/shared/common.yml
    inputs:
      component_context_dir: "$[[ inputs.component_context_dir ]]"
      job_name_prefix: "$[[ inputs.job_name_prefix ]]"
      job_stage: "$[[ inputs.job_stage ]]"
      _component_sha: "$[[ component.sha ]]"
      _component_version: "$[[ component.version ]]"
      java_version: "$[[ inputs.java_version ]]"

# =============================================================================
# Build JAR
# =============================================================================

"$[[ inputs.job_name_prefix ]]java::build":
  artifacts:
    expire_in: 1 week
    paths:
      - $[[ inputs.component_context_dir ]]/target/*.jar
  cache:
    key: "${CI_JOB_NAME}-$[[ inputs.java_version ]]"
    paths:
      - $[[ inputs.component_context_dir ]]/.m2-local/
    when: always
  extends: ".$[[ inputs.job_name_prefix ]]java::common"
  script: /component/build/jobs/package.sh
